from __future__ import annotations

from .contracts import SupportedLanguage


TEXT = {
    "ru": {
        "research_intro": "Я рассматриваю задачу в контексте открытой исследовательской страницы и не буду подменять отсутствующие данные предположениями.",
        "participant_intro": "Я помогу понять текущий этап участия, не раскрывая закрытые исследовательские данные и данные других участников.",
        "need_message": "Что именно вы хотите определить, проверить или сделать на этой странице?",
        "name_definition": "Как называется разрабатываемый объект и каково его предварительное определение?",
        "measurement": "Какими зарегистрированными вопросами, шкалами или измерительными источниками он будет измеряться?",
        "calculation": "Как ответы или измерения преобразуются в значение параметра?",
        "time": "Какое единое время наблюдения и какая временная шкала используются?",
        "data_source": "Какая модель или зарегистрированный результат измерений является источником данных?",
        "data_shape": "Какова единица наблюдения: участник, временной срез, повторное измерение или их сочетание?",
        "input_format": "Какой формат входного файла или потока определён системой?",
        "quality_profile": "Построен ли профиль пропусков, выбросов, временной регулярности и числовых диапазонов до выбора обработки?",
        "normalization_choice": "Какую цель должна решать нормировка и какие допустимые варианты нужно сравнить без изменения исходника?",
        "device_type": "Какой тип подключения использует устройство: камера/микрофон, Serial, USB, Bluetooth, сеть или файл?",
        "device_identity": "Укажите производителя и модель устройства; без этого нельзя надёжно выбирать драйвер или протокол.",
        "permission_state": "Предоставлено ли браузеру или операционной системе разрешение на доступ к устройству?",
        "measurement_goal": "Какую величину или сигнал должен получать этот инструмент и с какой частотой?",
        "training_source_folder": "Укажите папку с исходными изображениями в градациях серого.",
        "training_mask_folder": "Укажите отдельную папку с соответствующими ручными бинарными масками.",
        "training_output_folder": "В какую папку Google Drive сохранить манифесты, модель, порог и отчёт проверки?",
        "training_task": "Подтвердите задачу: изображение в градациях серого преобразуется в бинарную маску.",
        "training_independence": "По какому идентификатору разделять независимые группы: участник, сессия или исходное видео?",
        "method": "Какой статистический метод выбран и выполнены ли его предпосылки?",
        "result_trace": "Укажите идентификаторы расчёта, метода и входного снимка данных.",
        "quality": "Какие ограничения качества и пропуски должны сопровождать результат?",
        "project": "К какому проекту и этапу исследования относится эта задача?",
        "sources": "Какие научные источники уже зарегистрированы для этого утверждения?",
        "hypothesis_basis": "Какие наблюдения, зарегистрированные результаты, модели или научные источники составляют основание гипотезы?",
        "hypothesis_variables": "Какие измеряемые объекты выбраны и как распределены роли исхода, предиктора, медиатора, модератора, контроля и времени?",
        "hypothesis_statement": "Как сформулировано проверяемое отношение между выбранными объектами?",
        "hypothesis_falsification": "Какой наблюдаемый результат опровергнет гипотезу или не позволит считать её поддержанной?",
        "hypothesis_time": "Как задана временная последовательность измерений на единой оси UTC?",
        "hypothesis_analysis": "Какими методами будет проверяться гипотеза и как будут проверены предпосылки методов?",
        "hypothesis_predictor": "Какая величина или набор величин рассматриваются как предикторы зависимой величины?",
        "hypothesis_model_family": "Какое семейство зависимости соответствует типу исхода, структуре повторных измерений и предполагаемой форме связи?",
        "hypothesis_time_variable": "Подключена ли системой единая ось UTC и определено ли, как с ней сопоставляются моменты всех измерений?",
        "qualitative_research_question": "Какой главный открытый исследовательский вопрос связывает феномен, участников или случаи и контекст?",
        "qualitative_empirical_material": "Какой зарегистрированный эмпирический материал будет реально анализироваться: интервью, наблюдения, документы, ответы, измерения или результаты?",
        "qualitative_method": "Какой качественный аналитический подход совместим с этим вопросом и типом материала?",
        "qualitative_disconfirmation": "Какие отрицательные случаи, противоречащие данные или альтернативные объяснения потребуют пересмотра предположения?",
        "qualitative_trustworthiness": "Какими способами будут обеспечены прозрачность, рефлексивность и надёжность интерпретации?",
        "sensor_candidate_source": "Какой зарегистрированный сенсорный сигнал или вычисленный признак проверяется?",
        "sensor_anchor_source": "С чем независимо сопоставляется сенсор: эталонным прибором, физическим состоянием, анкетным результатом, параметром или разметкой события?",
        "sensor_pairing_contract": "Как значения разных источников сопоставляются по UTC, какова единица наблюдения и что считается независимой единицей?",
        "sensor_validation_method": "Какой совместимый метод проверяет именно выбранную цель: согласованность, рассогласование, динамику, конструктную связь или прогноз?",
        "sensor_discrepancy_definition": "Как шкалы приводятся к сопоставимому виду и какой метрикой определяется рассогласование?",
        "complete_missing": "Ответьте на уточняющие вопросы выше; после этого Рэй повторно проверит согласованность контекста.",
        "complete_review": "Контекст содержит обязательные элементы для следующего шага проверки.",
        "confirm_before_write": "Запись решения, вопроса или риска выполняется только после вашего подтверждения.",
        "action_question": "Открытый вопрос",
        "action_decision": "Решение проекта",
        "action_risk": "Исследовательский риск",
    },
    "en": {
        "research_intro": "I am reviewing the task in the context of the open research page and will not replace missing data with assumptions.",
        "participant_intro": "I can explain the current participation step without exposing restricted research data or other participants' data.",
        "need_message": "What do you want to define, verify, or do on this page?",
        "name_definition": "What is the developing object called, and what is its preliminary definition?",
        "measurement": "Which registered questions, scales, or measurement sources will measure it?",
        "calculation": "How are responses or measurements transformed into the parameter value?",
        "time": "Which unified observation time and temporal scale are used?",
        "data_source": "Which model or registered measurement result is the data source?",
        "data_shape": "What is the observation unit: participant, time slice, repeated measure, or a combination?",
        "input_format": "Which input file or stream format has the system detected?",
        "quality_profile": "Was a missingness, outlier, temporal-regularity and numeric-range profile built before choosing processing?",
        "normalization_choice": "What purpose should normalization serve, and which admissible options should be compared without modifying the raw input?",
        "device_type": "Which connection does the device use: camera/microphone, Serial, USB, Bluetooth, network, or file?",
        "device_identity": "Provide the device manufacturer and model; a driver or protocol cannot be selected reliably without them.",
        "permission_state": "Has browser or operating-system permission for the device been granted?",
        "measurement_goal": "Which quantity or signal should this instrument acquire, and at what frequency?",
        "training_source_folder": "Provide the folder containing the source grayscale images.",
        "training_mask_folder": "Provide a separate folder containing the corresponding manual binary masks.",
        "training_output_folder": "Which Google Drive folder should receive the manifests, model, threshold, and evaluation report?",
        "training_task": "Confirm the task: a grayscale image is transformed into a binary mask.",
        "training_independence": "Which identifier defines independent groups: participant, session, or source video?",
        "method": "Which statistical method is selected, and are its assumptions satisfied?",
        "result_trace": "Provide the calculation, method, and input data snapshot identifiers.",
        "quality": "Which quality limitations and missingness must accompany the result?",
        "project": "Which project and research stage does this task belong to?",
        "sources": "Which scientific sources are already registered for this claim?",
        "hypothesis_basis": "Which observations, registered results, models, or scientific sources form the hypothesis basis?",
        "hypothesis_variables": "Which measured objects are selected, and how are outcome, predictor, mediator, moderator, control, and time roles assigned?",
        "hypothesis_statement": "What testable relationship is stated between the selected objects?",
        "hypothesis_falsification": "Which observable result would falsify the hypothesis or prevent it from being considered supported?",
        "hypothesis_time": "How is temporal order defined on the unified UTC axis?",
        "hypothesis_analysis": "Which methods will test the hypothesis, and how will their assumptions be checked?",
        "hypothesis_predictor": "Which quantity or set of quantities are predictors of the dependent quantity?",
        "hypothesis_model_family": "Which model family matches the outcome type, repeated-measure structure, and expected relationship form?",
        "hypothesis_time_variable": "Has the system attached the unified UTC axis, and is the alignment of every measurement time defined?",
        "qualitative_research_question": "What open central research question connects the phenomenon, participants or cases, and context?",
        "qualitative_empirical_material": "Which registered empirical material will actually be analysed: interviews, observations, documents, responses, measurements, or results?",
        "qualitative_method": "Which qualitative analytic approach is compatible with this question and material type?",
        "qualitative_disconfirmation": "Which negative cases, contradictory evidence, or rival explanations would require revising the proposition?",
        "qualitative_trustworthiness": "How will transparency, reflexivity, and trustworthiness of interpretation be supported?",
        "sensor_candidate_source": "Which registered sensor signal or derived feature is being evaluated?",
        "sensor_anchor_source": "What independent anchor is used: reference instrument, physical state, questionnaire result, parameter, or event annotation?",
        "sensor_pairing_contract": "How are sources paired in UTC, what is the observation unit, and what is the independent unit?",
        "sensor_validation_method": "Which compatible method tests the selected aim: agreement, discordance, dynamics, construct relationship, or prediction?",
        "sensor_discrepancy_definition": "How are scales harmonized, and which metric defines discordance?",
        "complete_missing": "Answer the clarification questions above; Ray will then recheck context consistency.",
        "complete_review": "The context contains the required elements for the next review step.",
        "confirm_before_write": "A decision, question, or risk is recorded only after your confirmation.",
        "action_question": "Open question",
        "action_decision": "Project decision",
        "action_risk": "Research risk",
    },
    "es": {
        "research_intro": "Reviso la tarea en el contexto de la página científica abierta y no sustituiré los datos ausentes por supuestos.",
        "participant_intro": "Puedo explicar la etapa actual de participación sin revelar datos restringidos ni datos de otros participantes.",
        "need_message": "¿Qué desea definir, comprobar o hacer en esta página?",
        "name_definition": "¿Cómo se llama el objeto en desarrollo y cuál es su definición preliminar?",
        "measurement": "¿Qué preguntas, escalas o fuentes de medición registradas lo medirán?",
        "calculation": "¿Cómo se transforman las respuestas o mediciones en el valor del parámetro?",
        "time": "¿Qué tiempo unificado de observación y qué escala temporal se utilizan?",
        "data_source": "¿Qué modelo o resultado de medición registrado es la fuente de datos?",
        "data_shape": "¿Cuál es la unidad de observación: participante, corte temporal, medida repetida o una combinación?",
        "input_format": "¿Qué formato de archivo o flujo de entrada detectó el sistema?",
        "quality_profile": "¿Se creó un perfil de datos faltantes, valores atípicos, regularidad temporal y rangos antes de elegir el procesamiento?",
        "normalization_choice": "¿Qué objetivo debe cumplir la normalización y qué opciones admisibles deben compararse sin cambiar los datos originales?",
        "device_type": "¿Qué conexión usa el dispositivo: cámara/micrófono, Serial, USB, Bluetooth, red o archivo?",
        "device_identity": "Indique fabricante y modelo; sin ellos no puede elegirse de forma fiable un controlador o protocolo.",
        "permission_state": "¿Se concedió al navegador o al sistema operativo permiso para acceder al dispositivo?",
        "measurement_goal": "¿Qué magnitud o señal debe adquirir el instrumento y con qué frecuencia?",
        "training_source_folder": "Indique la carpeta con las imágenes originales en escala de grises.",
        "training_mask_folder": "Indique otra carpeta con las máscaras binarias manuales correspondientes.",
        "training_output_folder": "¿En qué carpeta de Google Drive se guardarán manifiestos, modelo, umbral e informe?",
        "training_task": "Confirme la tarea: transformar una imagen en escala de grises en una máscara binaria.",
        "training_independence": "¿Qué identificador define grupos independientes: participante, sesión o video de origen?",
        "method": "¿Qué método estadístico se seleccionó y se cumplen sus supuestos?",
        "result_trace": "Indique los identificadores del cálculo, método y captura de datos de entrada.",
        "quality": "¿Qué limitaciones de calidad y datos ausentes deben acompañar el resultado?",
        "project": "¿A qué proyecto y etapa de investigación pertenece esta tarea?",
        "sources": "¿Qué fuentes científicas están registradas para esta afirmación?",
        "hypothesis_basis": "¿Qué observaciones, resultados registrados, modelos o fuentes científicas forman la base de la hipótesis?",
        "hypothesis_variables": "¿Qué objetos medidos se eligieron y cómo se asignan las funciones de resultado, predictor, mediador, moderador, control y tiempo?",
        "hypothesis_statement": "¿Qué relación comprobable se formula entre los objetos seleccionados?",
        "hypothesis_falsification": "¿Qué resultado observable refutaría la hipótesis o impediría considerarla respaldada?",
        "hypothesis_time": "¿Cómo se define el orden temporal en el eje UTC unificado?",
        "hypothesis_analysis": "¿Qué métodos comprobarán la hipótesis y cómo se verificarán sus supuestos?",
        "hypothesis_predictor": "¿Qué magnitud o conjunto de magnitudes predice la variable dependiente?",
        "hypothesis_model_family": "¿Qué familia de modelo corresponde al tipo de resultado, las medidas repetidas y la forma esperada de relación?",
        "hypothesis_time_variable": "¿El sistema conectó el eje UTC unificado y se definió cómo alinear el tiempo de cada medición?",
        "qualitative_research_question": "¿Qué pregunta central abierta conecta el fenómeno, participantes o casos y contexto?",
        "qualitative_empirical_material": "¿Qué material empírico registrado se analizará realmente: entrevistas, observaciones, documentos, respuestas, mediciones o resultados?",
        "qualitative_method": "¿Qué enfoque cualitativo es compatible con la pregunta y el tipo de material?",
        "qualitative_disconfirmation": "¿Qué casos negativos, datos contradictorios o explicaciones rivales exigirían revisar la proposición?",
        "qualitative_trustworthiness": "¿Cómo se garantizarán la transparencia, reflexividad y credibilidad de la interpretación?",
        "sensor_candidate_source": "¿Qué señal de sensor registrada o característica derivada se evalúa?",
        "sensor_anchor_source": "¿Qué referencia independiente se usa: instrumento patrón, estado físico, cuestionario, parámetro o evento anotado?",
        "sensor_pairing_contract": "¿Cómo se emparejan las fuentes en UTC, cuál es la unidad de observación y cuál la unidad independiente?",
        "sensor_validation_method": "¿Qué método compatible prueba el objetivo: concordancia, discordancia, dinámica, relación de constructo o predicción?",
        "sensor_discrepancy_definition": "¿Cómo se armonizan las escalas y qué métrica define la discordancia?",
        "complete_missing": "Responda a las preguntas de aclaración; después Ray volverá a comprobar la coherencia del contexto.",
        "complete_review": "El contexto contiene los elementos obligatorios para la siguiente revisión.",
        "confirm_before_write": "Una decisión, pregunta o riesgo se registra solo después de su confirmación.",
        "action_question": "Pregunta abierta",
        "action_decision": "Decisión del proyecto",
        "action_risk": "Riesgo de investigación",
    },
}


def localized(language: SupportedLanguage, key: str) -> str:
    return TEXT[language.value][key]
